create table APPLICATION(
    -- ID
    A_Id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

    -- Application Info
    S_Id int(11) UNSIGNED NOT NULL,
    Pr1_P_Id int(11) UNSIGNED NOT NULL,
    Pr2_P_Id int(11) UNSIGNED DEFAULT NULL,
    Pr3_P_Id int(11) UNSIGNED DEFAULT NULL,
    Pr4_P_Id int(11) UNSIGNED DEFAULT NULL,
    Pr5_P_Id int(11) UNSIGNED DEFAULT NULL,

    -- Optional Special Requirement Check
    OptReqsCheck varchar(20) NOT NULL DEFAULT '',

    Secret varchar(16) NOT NULL DEFAULT '',
    CreatedTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastUpdatedTime TIMESTAMP NOT NULL DEFAULT '1970-01-02 15:04:05',
    -- LastUpdatedTime TIMESTAMP NOT NULL CURRENT_TIMESTAMP,

    PRIMARY KEY (A_Id),
 
    INDEX (S_Id),
    INDEX (Pr1_P_Id, Pr2_P_Id, Pr3_P_Id, Pr4_P_Id, Pr5_P_Id),

    FOREIGN KEY (S_Id) REFERENCES STUDENT(S_Id) ON UPDATE CASCADE ON DELETE RESTRICT,

    FOREIGN KEY (Pr1_P_Id) REFERENCES PROJECT_INFO(P_Id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (Pr2_P_Id) REFERENCES PROJECT_INFO(P_Id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (Pr3_P_Id) REFERENCES PROJECT_INFO(P_Id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (Pr4_P_Id) REFERENCES PROJECT_INFO(P_Id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (Pr5_P_Id) REFERENCES PROJECT_INFO(P_Id) ON UPDATE CASCADE ON DELETE RESTRICT

) ENGINE=InnoDB DEFAULT CHARSET=utf8;
